#ERROR    [2025-01-02 09:43:51,966] - test.py:51 - __main__ - Важно! Это лог с ошибкой!
