[2025-01-03 12:57:29,681] #ERROR    module_1.py:39 - module_1:main - Лог1 ERROR
